# Generated by Django 2.2.2 on 2020-06-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkyticsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('corporate_headoffice', 'Corporate Headoffice'), ('delhi', 'Delhi'), ('bangalore', 'Bangalore'), ('kolkata', 'Kolkata')], default='corporate_headoffice', max_length=40, verbose_name='*Location')),
                ('description', models.TextField(verbose_name='*Incident Description')),
                ('date', models.DateField(verbose_name='*Date of Incident')),
                ('time', models.TimeField(verbose_name='*Time of Incident')),
                ('incident_location', models.TextField(blank=True, null=True, verbose_name='Incident Location')),
                ('initial_severity', models.CharField(choices=[('moderate', 'Moderate'), ('low', 'Low'), ('high', 'High')], default='moderate', max_length=20, verbose_name='*Intial severity')),
                ('suspected_cause', models.TextField(blank=True, null=True, verbose_name='Suspected Cause')),
                ('immediate_actions_taken', models.TextField(blank=True, null=True, verbose_name='Immediate Actions Taken')),
                ('is_environmental_incident', models.BooleanField(default=False, verbose_name='Sub Incident Types')),
                ('is_injury', models.BooleanField(default=False)),
                ('is_property_damage', models.BooleanField(default=False)),
                ('is_vehicle', models.BooleanField(default=False)),
                ('reported_by', models.CharField(max_length=100, verbose_name='*Reported By')),
            ],
        ),
    ]
